n1 = int(input())
n2 = int(input())
print('A soma entre {} e {} vale {}'.format(n1, n2, n1+n2), end = ' ')
print('A subtração entre {} e {} vale {}'.format(n1, n2, n1-n2))
print('A multiplicação entre {} e {} vale {}'.format(n1, n2, n1*n2))
print('A divisão entre {} e {} vale {:.3f}'.format(n1, n2, n1/n2))
print('A divisão inteira entre {} e {} vale {}'.format(n1, n2, n1 // n2))
print('A potência de {} elevado a {} vale {}'.format(n1, n2, n1**n2))
print('O resto da divisão de {} por {} vale {}'.format(n1, n2, n1%n2))
